# https://taskfile.dev

version: '3'

vars:
  package_name: sparql

tasks:
  code:check:
    desc: Check whether code formatting rules apply.
    cmds:
      - poetry run ruff format --check {{.package_name}} tests
      - poetry run ruff check {{.package_name}} tests

  code:
    desc: Format and standardise code.
    cmds:
      - poetry run ruff format {{.package_name}} tests
      - poetry run ruff --fix {{.package_name}} tests

  test:
    desc: Run Python tests.
    cmds:
      - poetry run pytest