name: Build and Upload Wheel on Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install project
        run: poetry install --no-interaction

      - name: Build wheel
        run: poetry build -f wheel

      - name: Upload wheel to release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/*.whl
          asset_name: your_project_name-${{ github.event.release.tag_name }}.whl
          asset_content_type: application/octet-stream
